import Contents from '../components/Contents'

const ProjectsPage = () => {
  const articles = [
    { id: 'jgi-genome-portal', title: 'JGI Genome Portal' },
    {
      id: 'biopig-hadoop-based-genomic-analysis-toolkit',
      title: 'BioPig: Hadoop-based Genomic Analysis Toolkit'
    },
    {
      id: 'jitterbit-data-integration-platform-ipaas',
      title: 'Jitterbit Data Integration Platform (iPaaS)'
    },
    {
      id: 'commerceroute-data-integration-and-workflow-solutions',
      title: 'CommerceRoute Data Integration and Workflow Solutions'
    },
    {
      id: 'query-estimator-for-petabyte-storage-systems',
      title: 'Query Estimator for Petabyte Storage Systems'
    },
    {
      id: 'compressed-bitmap-index-implementation',
      title: 'Compressed Bitmap Index Implementation'
    },
    {
      id: 'cosmic-microwave-background-cmb-spectrum-analysis',
      title: 'Cosmic Microwave Background (CMB) Spectrum Analysis'
    },
    { id: 'isotopes-explorer', title: 'Isotopes Explorer' },
    { id: 'batmud', title: 'BatMUD' }
  ]

  return (
    <main className="page-with-contents">
      <Contents articles={articles} />
      <section className="card-grid">

        <div className="card" id="jgi-genome-portal">
          <div className="card-title">JGI Genome Portal</div>
          <div className="card-text">The Genome Portal is a large-scale web site providing researchers globally with tools to
            access and interpret petabytes of genomic data generated by the Joint Genome Institute. As Team Lead, I was
            responsible for this portal, which provides access to data at multiple stages of genome analysis and annotation
            pipelines. This work also included overseeing the shift to Jenkins for build and deployment automation, replacing
            older Perl scripts.</div>
        </div>

        <div className="card" id="biopig-hadoop-based-genomic-analysis-toolkit">
          <div className="card-title">BioPig: Hadoop-based Genomic Analysis Toolkit</div>
          <div className="card-text">This project involved developing BioPig, a Hadoop-based framework extending Apache Pig,
            specifically designed for large-scale genomic data analysis. This toolkit was introduced to address the "data
            deluge" resulting from the exponential growth of sequence data, making it one of the key solutions that scale to
            handle massive data and computational needs in bioinformatics.</div>
        </div>

        <div className="card" id="jitterbit-data-integration-platform-ipaas">
          <div className="card-title">Jitterbit Data Integration Platform (iPaaS)</div>
          <div className="card-text">As a co-founder and Chief Software Architect, I developed Jitterbit into a cloud-based
            data integration company recognized as a leader and visionary in the iPaaS field. The solution expanded a prior
            product to include the ability to call and host web services, offering visual mapping for integration across
            structures like XML, databases, LDAP directories, and multiple cloud applications (e.g., Salesforce.com,
            NetSuite). I also completed the porting of the data integration and workflow software to Solaris and Linux and
            made it open source, contributing to the Apache Axis web service framework in the process.</div>
        </div>

        <div className="card" id="commerceroute-data-integration-and-workflow-solutions">
          <div className="card-title">CommerceRoute Data Integration and Workflow Solutions</div>
          <div className="card-text">This suite of products began with the architecture and implementation of SilkRoute (later
            WebWorkflow), a core workflow/Business Process Modeling product featuring a client tool, a rule database, and an
            engine written in C++ and ported to Linux and Solaris. Building upon this powerful engine, I developed the
            CommerceRoute data integration solution, which handles transformations and transfers between sources and targets
            (including FTP, SAP, databases, and formats like XML/EDI) and implements the RosettaNet B2B framework. The
            complete solution was later sold as the Syncx integration appliance, reducing support costs by limiting customer
            access strictly to a web browser.</div>
        </div>

        <div className="card" id="query-estimator-for-petabyte-storage-systems">
          <div className="card-title">Query Estimator for Petabyte Storage Systems</div>
          <div className="card-text">This component was developed as part of a Department of Energy (DOE) Grand Challenge
            project focused on handling petabytes of data stored on robotic tape systems (HPSS). The Query Estimator utilizes
            a researched and implemented compressed bitmap index to quickly estimate the size of a result set for a particular
            query before the data retrieval request is executed, optimizing access to massive multi-dimensional datasets. The
            distributed system coordinating this storage access relied on CORBA for inter-component communication.</div>
        </div>

        <div className="card" id="compressed-bitmap-index-implementation">
          <div className="card-title">Compressed Bitmap Index Implementation</div>
          <div className="card-text">I researched and implemented a specialized compressed bitmap index that is highly
            effective for range queries. A key feature of this work is the ability to perform query execution directly without
            needing to decompress the index first, enhancing performance for high-dimensional data problems. This work was
            published in a scientific paper titled "Notes on Design and Implementation of Compressed Bit Vectors".</div>
        </div>

        <div className="card" id="cosmic-microwave-background-cmb-spectrum-analysis">
          <div className="card-title">Cosmic Microwave Background (CMB) Spectrum Analysis</div>
          <div className="card-text">This research involved a detailed analysis of observations related to the Cosmic
            Microwave Background (CMB) radiation intensity, a relic of the Big Bang. The resulting analysis provided new,
            more precise values for the best fit temperature of the CMB (2.7356 ± 0.0038 K at 95% CL) and calculated the speed
            of our solar system relative to the CMB.</div>
        </div>

        <div className="card" id="isotopes-explorer">
          <div className="card-title">Isotopes Explorer</div>
          <div className="card-text">A visualization tool for nuclei of isotopes.</div>
        </div>

        <div className="card" id="batmud">
          <div className="card-title">BatMUD</div>
          <div className="card-text">A MUD (Multi-User Dungeon) is an online role-playing game. In 1991 I was at the
            university and joined BatMUD as a player. I wizzed (reached level 20 and beat Tiamat) and started extending the
            game as all wizards do. This is how I discovered my love of programming. I started working on the, adding a
            'feelings' system and the first global event (orch raids). The coding for LPC MUDs is in LPC, an object-oriented
            language version of C.</div>
        </div>

        <div className="card hidden">
          <div className="card-title">.</div>
          <div className="card-text">.
          </div>
          <div className="card-subtitle pt-4">.</div>
        </div>
      </section>
    </main>
  )
}

export default ProjectsPage;
