/**
 * Canonical ML Wiki content contract (generated by scripts/ml-wiki or hand-maintained).
 */

export const WIKI_DOMAINS = [
  "math",
  "foundations",
  "supervised",
  "unsupervised",
  "deep-learning",
  "llm",
  "evaluation",
  "history",
  "other",
] as const;

export type WikiDomain = (typeof WIKI_DOMAINS)[number];

export const WIKI_LEVELS = ["basic", "intro", "intermediate", "advanced"] as const;
export type WikiLevel = (typeof WIKI_LEVELS)[number];

export const WIKI_TYPES = [
  "definition",
  "intuition",
  "proof",
  "example",
  "pitfall",
  "mixed",
] as const;
export type WikiContentType = (typeof WIKI_TYPES)[number];

export const SECTION_KINDS = [
  "prose",
  "definition",
  "theorem",
  "example",
  "pitfall",
  "equation",
  "figure",
] as const;
export type WikiSectionKind = (typeof SECTION_KINDS)[number];

export type WikiFigure = {
  src: string;
  alt: string;
  caption?: string;
  width?: number;
  height?: number;
};

export type WikiSection = {
  kind: WikiSectionKind;
  title?: string;
  /** Plain text or HTML (trusted: repo-generated only). */
  body?: string;
  /** Display math (TeX), without delimiters or with $$ — normalized at import time. */
  equation?: string;
  figure?: WikiFigure;
  /** Source note IDs that contributed to this section (import pipeline). */
  sourceCardIds?: string[];
};

export type WikiCard = {
  noteId: string;
  prompt: string;
  answer: string;
  tags: string[];
  mediaRefs?: string[];
};

/** Optional bibliography line (merge from card “References” fields at import time). */
export type WikiPaperRef = {
  citation: string;
  url?: string;
  /** Plain DOI without https://doi.org/ prefix */
  doi?: string;
  note?: string;
};

export type WikiTopic = {
  slug: string;
  title: string;
  summary: string;
  domain: WikiDomain;
  level: WikiLevel;
  type: WikiContentType;
  /** Free-form tags for /ml/wiki/tags/[tag] */
  tags: string[];
  prerequisites: string[];
  related: string[];
  sections: WikiSection[];
  cards: WikiCard[];
  updatedAt: string;
  sourceDeck: string;
  /** Optional HTML: historical context, naming, who/when. */
  historyHtml?: string;
  /** Optional HTML: general references (books, surveys, course notes). */
  referencesHtml?: string;
  /** Curated paper list (often mirrored from flashcard reference fields). */
  papers?: WikiPaperRef[];
};

/** Lightweight row for index and generateStaticParams */
export type WikiTopicIndexEntry = Pick<
  WikiTopic,
  | "slug"
  | "title"
  | "summary"
  | "domain"
  | "level"
  | "type"
  | "tags"
  | "prerequisites"
  | "related"
  | "updatedAt"
  | "sourceDeck"
>;

export type WikiManifest = {
  version: 1;
  updatedAt: string;
  sourceDeck: string;
  topics: WikiTopicIndexEntry[];
};

export interface PathCriteria {
  includeTags: string[]; // Let's interpret this as OR (matching 'or' user preference)
  excludeTags?: string[];
  levels?: ("intro" | "basic" | "intermediate" | "advanced")[];
}

export type WikiLearningPath = {
  slug: string;
  title: string;
  description: string;
  criteria: PathCriteria;
  estimatedMinutes?: number;
};

export type WikiPathsFile = {
  version: 1;
  paths: WikiLearningPath[];
};
